// Code generated by MockGen. DO NOT EDIT.
// Source: backend/internal/biz/greeter.go

package mocks

import (
	"context"
	"reflect"

	"backend/internal/biz"
	"github.com/golang/mock/gomock"
)

// MockGreeterRepo is a mock of GreeterRepo interface.
type MockGreeterRepo struct {
	ctrl     *gomock.Controller
	recorder *MockGreeterRepoMockRecorder
}

// MockGreeterRepoMockRecorder is the mock recorder for MockGreeterRepo.
type MockGreeterRepoMockRecorder struct {
	mock *MockGreeterRepo
}

// NewMockGreeterRepo creates a new mock instance.
func NewMockGreeterRepo(ctrl *gomock.Controller) *MockGreeterRepo {
	mock := &MockGreeterRepo{ctrl: ctrl}
	mock.recorder = &MockGreeterRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGreeterRepo) EXPECT() *MockGreeterRepoMockRecorder {
	return m.recorder
}

// FindByID mocks base method.
func (m *MockGreeterRepo) FindByID(ctx context.Context, id int64) (*biz.Greeter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*biz.Greeter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockGreeterRepoMockRecorder) FindByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockGreeterRepo)(nil).FindByID), ctx, id)
}

// ListAll mocks base method.
func (m *MockGreeterRepo) ListAll(ctx context.Context) ([]*biz.Greeter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]*biz.Greeter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockGreeterRepoMockRecorder) ListAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockGreeterRepo)(nil).ListAll), ctx)
}

// ListByHello mocks base method.
func (m *MockGreeterRepo) ListByHello(ctx context.Context, hello string) ([]*biz.Greeter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByHello", ctx, hello)
	ret0, _ := ret[0].([]*biz.Greeter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByHello indicates an expected call of ListByHello.
func (mr *MockGreeterRepoMockRecorder) ListByHello(ctx, hello interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByHello", reflect.TypeOf((*MockGreeterRepo)(nil).ListByHello), ctx, hello)
}

// Save mocks base method.
func (m *MockGreeterRepo) Save(ctx context.Context, greeter *biz.Greeter) (*biz.Greeter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, greeter)
	ret0, _ := ret[0].(*biz.Greeter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Save indicates an expected call of Save.
func (mr *MockGreeterRepoMockRecorder) Save(ctx, greeter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockGreeterRepo)(nil).Save), ctx, greeter)
}

// Update mocks base method.
func (m *MockGreeterRepo) Update(ctx context.Context, greeter *biz.Greeter) (*biz.Greeter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, greeter)
	ret0, _ := ret[0].(*biz.Greeter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockGreeterRepoMockRecorder) Update(ctx, greeter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGreeterRepo)(nil).Update), ctx, greeter)
}