server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:root@tcp(127.0.0.1:3306)/test?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  vector:
    milvus:
      host: 127.0.0.1
      port: 19530
      username: ""
      password: ""
      database: "default"
    embedding:
      provider: "openai"  # openai, azure, local
      api_key: ""
      base_url: "https://api.openai.com/v1"
      model: "text-embedding-ada-002"
      timeout: 30
ai:
  models:
    # 默认模型配置
    default:
      provider: "deepseek"
      model_name: "deepseek-reasoner"
      api_key: "${DEEPSEEK_API_KEY}"
      base_url: "https://api.deepseek.com/"
      temperature: 0.8
      max_tokens: 4096
      top_p: 1.0
      timeout: 300s
    # 可选的其他模型配置
    creative:
      provider: "deepseek"
      model_name: "deepseek-chat"
      api_key: "${DEEPSEEK_API_KEY}"
      base_url: "https://api.deepseek.com/"
      temperature: 1.0
      max_tokens: 4096
      top_p: 0.9
      timeout: 300s
    reasoning:
      provider: "deepseek"
      model_name: "deepseek-reasoner"
      api_key: "${DEEPSEEK_API_KEY}"
      base_url: "https://api.deepseek.com/"
      temperature: 0.3
      max_tokens: 8192
      top_p: 0.8
      timeout: 600s
